openapi: 3.0.0
info:
  title: API de Interacciones MySQL
  version: 1.0.0
paths:
  /dmusic/artists:
    get:
      tags:
        - Interacciones MySQL
      summary: Obtiene todos los artistas
      description: Obtiene todos los artistas en la base de datos.
      responses:
        '200':
          description: Lista de artistas obtenida exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
        '400':
          description: No hay artistas en la base de datos.
        '500':
          description: Error de sistema.

  /dmusic/songs:
    get:
      tags:
        - Interacciones MySQL
      summary: Obtiene todas las canciones
      description: Obtiene todas las canciones en la base de datos.
      responses:
        '200':
          description: Lista de canciones obtenida exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
        '400':
          description: No hay canciones en la base de datos.
        '500':
          description: Error de sistema.

  /dmusic/search:
    post:
      tags:
        - Interacciones MySQL
      summary: Buscar canción
      description: Buscar canción mediante su título.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - song
              properties:
                song:
                  type: string
                  description: Título de la canción
      responses:
        '200':
          description: Canción obtenida exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
        '400':
          description: No hay canciones con este título.
        '500':
          description: Error de sistema.

  /dmusic/play-song:
    post:
      tags:
        - Interacciones MySQL
      summary: Reproducir una canción.
      description: Reproducir una canción tramite su id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id_song
              properties:
                id_song:
                  type: string
                  description: id de la canción
      responses:
        200:
          description: Canción reproduciendo exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
        500:
          description: Error de sistema.
  
  /dmusic/play-artist:
    post:
      tags:
        - Interacciones MySQL
      summary: Reproducir canciones de un artista.
      description: Reproducir canciones de un artista predefinido tramite su id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id_artist
              properties:
                id_artist:
                  type: string
                  description: id del artista
      responses:
        200:
          description: Artista reproduciendo exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
        500:
          description: Error de sistema.
  
  /dmusic/play-library:
   post:
     tags:
       - Interacciones MySQL
     summary: Reproducir librería personal.
     description: Reproducir canciones que el usuario tiene entre los favoritos.
     requestBody:
       required: true
       content:
         application/json:
           schema:
             type: object
             required:
               - id_user
               - id_song
             properties:
               id_user:
                 type: string
                 description: id del usuario
               id_song:
                 type: string
                 description: id de la canción
     responses:
       200:
         description: Canciones favoritas reproduciendo exitosamente.
         content:
           application/json:
             schema:
               type: object
               properties:
                 data:
                   type: array
                   items:
                     type: object
       500:
         description: Error de sistema.
  
  /dmusic/add-favoritesongs:
     post:
       tags: 
          - Interacciones MySQL
       summary: Añadir cancion a lista favoritos.
       description: Añadir canción a lista favoritos en la librería personal.
     requestBody:
       required: true
       content:
         application/json:
           schema:
             type: object
             required:
               - id_user
               - id_song
             properties:
               id_user:
                 type: string
                 description: id del usuario
               id_song:
                 type: string
                 description: id de la canción
     responses:
       200:
         description: Canción añadida a favoritos exitosamente.
         content:
           application/json:
             schema:
               type: object
               properties:
                 message:
                   type: string
       400:
         description: La cancion ya esta en tus favoritos.
       500:
         description: Error de sistema.
  
  /dmusic/delete-favoritesongs:
    delete:
      tags:
        - Interacciones MySQL
      summary: Eliminar canción de lista favoritos.
      description: Eliminar canción de lista favoritos según su ID y el ID del usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id_user
                - id_song
              properties:
                id_user:
                  type: string
                  description: id del usuario
                id_song:
                  type: string
                  description: id de la canción
      responses:
        200:
          description: Canción eliminada exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        500:
          description: Error de sistema.
  
  /dmusic/favoritesongs:
    post:
      tags:
        - Interacciones MySQL
      summary: Lista canciones favoritas.
      description: Obtiene la lista de todas las canciones añadidas a los favoritos.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id_user:
                  type: string
                  description: id del usuario
      responses:
        200:
          description: Lista favoritos obtenida exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
        400:
          description: No hay canciones favoritas en la base de datos.
        500:
          description: Error de sistema.
  
  